version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - nest-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/flight-booking?authSource=admin
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge

volumes:
  mongo-data:
